CREATE TABLE IF NOT EXISTS wines (
    wine_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wine_name TEXT NOT NULL,
    winery TEXT NOT NULL,
    varietal TEXT NOT NULL,
    vintage TEXT,
    rating TEXT NOT NULL,
    notes TEXT,
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE NOT NULL
);